name: GitHub Metrics

on:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC
  workflow_dispatch: {}

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: adityagarud
          template: classic
          base: header, repositories, activity, community, metadata
          config_timezone: Asia/Kolkata
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: yashranaway
          # Add or tweak plugins below as desired
          plugin_followup: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_stars: yes
          plugin_lines: yes
